# -*- coding: utf-8 -*-
"""Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cz_Jj1qJKwBDhV-i_4qVG4C0XbW-BxeW
"""

# app.py
# Streamlit app that FIRST asks user to upload a CSV, then builds LPA + ML pipeline and shows dashboard.
# Place this file in a folder where you can run: `streamlit run app.py`

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import plotly.express as px
import plotly.graph_objects as go
from sklearn.preprocessing import StandardScaler
from sklearn.mixture import GaussianMixture

st.set_page_config(page_title="LPA + ML Dashboard", layout="wide")

st.title("🚀 Employee Profiling Dashboard (LPA + ML Predictions)")
st.write("Upload your dataset and analyze employee profiles instantly.")

# -------------------------
# Upload Dataset
# -------------------------
uploaded = st.file_uploader("Upload your CSV", type=["csv"])

if uploaded is None:
    st.info("Please upload a dataset to continue.")
    st.stop()

df = pd.read_csv(uploaded)
st.success(f"Uploaded dataset with {df.shape[0]} rows and {df.shape[1]} columns.")

st.dataframe(df.head())

# -------------------------
# Run LPA (FAST)
# -------------------------
st.subheader("🎯 Latent Profile Analysis (LPA)")

lpa_features = [
    "PerformanceScore","Satisfaction","Engagement",
    "Motivation","Stress","WorkLifeBalance"
]

X = df[lpa_features].dropna()
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

gmm = GaussianMixture(n_components=3, random_state=42)
df["LPA_Profile"] = gmm.fit_predict(X_scaled)

st.success("LPA completed successfully!")

# -------------------------
# Load Pretrained Model
# -------------------------
st.subheader("🤖 Load ML Model")

try:
    model = joblib.load("best_model_attrition.joblib")
    preprocessor = joblib.load("preprocessor.joblib")
except:
    st.error("❌ Missing model artifacts. Upload best_model_attrition.joblib & preprocessor.joblib to the same folder.")
    st.stop()

# -------------------------
# KPI CARDS
# -------------------------
col1, col2, col3, col4 = st.columns(4)

col1.metric("Avg Satisfaction", f"{df['Satisfaction'].mean():.2f}")
col2.metric("Avg Performance", f"{df['PerformanceScore'].mean():.2f}")
col3.metric("Profiles", df["LPA_Profile"].nunique())
col4.metric("Employees", df.shape[0])

# -------------------------
# Plot Profile Distribution
# -------------------------
st.subheader("📊 LPA Profile Distribution")

fig1 = px.bar(df["LPA_Profile"].value_counts().reset_index(),
              x="index", y="LPA_Profile",
              title="Employees per Profile")
st.plotly_chart(fig1, use_container_width=True)

# -------------------------
# Employee Drilldown
# -------------------------
st.subheader("🔍 Employee Drilldown")

emp_id = st.selectbox("Select EmployeeID", df["EmployeeID"].unique())
emp_row = df[df["EmployeeID"] == emp_id]

st.write(emp_row)

# -------------------------
# Prediction
# -------------------------
st.subheader("🔮 Attrition Prediction")

features_needed = preprocessor.feature_names_in_
X_emp = preprocessor.transform(emp_row[features_needed])
prob = model.predict_proba(X_emp)[0,1]
label = "High Risk" if prob >= 0.5 else "Low Risk"

st.write(f"Prediction: **{label}**")
gauge = go.Figure(go.Indicator(
    mode="gauge+number",
    value=prob*100,
    title={'text': "Attrition Risk (%)"},
    gauge={'axis': {'range': [0,100]}}
))
st.plotly_chart(gauge, use_container_width=True)

st.success("Dashboard Ready!")
